### ISSUE TITLE
Starting container with HostConfig removed in Docker 1.12 - extra_start_kwargs fails

### ISSUE THREAD

**Issue by WillEngler** [jupyterhub/jupyterhub-deploy-docker#16]
When an authenticated user starts a server, I see this exception:

```docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}'")```

Not sure if this is the right diagnosis, but it seems like the [extra_start_kwargs](https://github.com/jupyterhub/jupyterhub-deploy-docker/blob/master/jupyterhub_config.py#L30) get passed to the docker-py client [here](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L414) in dockerspawner, and then gets packaged into HostConfig [in docker-py](https://github.com/docker/docker-py/blob/master/docker/api/container.py#L379). And in Docker 1.12 this is disallowed. Maybe this is really a bug in dockerspawner? Or - best case scenario - I'm just configuring something wrong.

Hiccups aside, this reference deployment is really helpful. Thanks!

A full stack trace for reference:
```
[E 2016-07-31 01:09:45.313 JupyterHub web:1524] Uncaught exception GET /hub/user/willengler (172.18.0.1)
     HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/hub/user/willengler', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Host': 'localhost:8000', 'Upgrade-Insecure-Requests': '1', 'Referer': 'http://localhost:8000/hub/home', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 'Connection': 'keep-alive', 'Dnt': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Cookie': 'jupyter-hub-token="2|1:0|10:1469923076|17:jupyter-hub-token|44:OTAxYjcyNjUwYTkxNGVlYjhkZGI2M2IyNmE0NDIxMTc=|6e8cf80adff7387db0538fe75140850b7d4ba39a01acb4f6bb31c0d6385d171f"; csrftoken=MS6Px1V3vBda1ETy6pL7oO8plbJI5AZZ', 'Accept-Encoding': 'gzip, deflate, sdch'})
     Traceback (most recent call last):
       File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
         result = yield result
       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 494, in get
         yield self.spawn_single_user(current_user)
       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 312, in spawn_single_user
         yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 247, in spawn
         raise e
       File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 228, in spawn
         yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
       File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 416, in start
         yield self.docker('start', self.container_id, **start_kwargs)
       File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
         return self.__get_result()
       File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
         raise self._exception
       File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
         result = self.fn(*self.args, **self.kwargs)
       File "/opt/conda/lib/python3.5/site-packages/dockerspawner/dockerspawner.py", line 292, in _docker
         return m(*args, **kwargs)
       File "/opt/conda/lib/python3.5/site-packages/docker/utils/decorators.py", line 21, in wrapped
         return f(self, resource_id, *args, **kwargs)
       File "/opt/conda/lib/python3.5/site-packages/docker/api/container.py", line 368, in start
         self._raise_for_status(res)
       File "/opt/conda/lib/python3.5/site-packages/docker/client.py", line 174, in _raise_for_status
         raise errors.APIError(e, response, explanation=explanation)
     docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}'")
```

**Comment by jtyberg** [comment]
@WillEngler Thanks for testing on the new Docker release.  I was able to reproduce.

A lot of changes went into 1.12, and we're hitting one of them.  The fix is not to pass any host configuration in the `extra_start_kwargs`, including the `network_mode`.  

I'm of the mindset that we should support the latest Docker Engine, so I'll create a PR to fix, even though the deployment may not work with older versions of Docker.

**Comment by WillEngler** [comment]
Thanks for all the hard work, Jupyter team!
