### ISSUE TITLE
database schema version woes

### ISSUE THREAD

**Issue by Heerpa** [jupyterhub/jupyterhub-deploy-docker#87]
Hi!
I've been happily using jupyterhub from docker in a local, well firewalled university network. 

Recently I wanted to update my underlying user image and have rebuilt the whole jupyterhub/postgresql/singleuser setup. Building works fine but when I start the hub I get the following error:

````
Starting up JupyterHub
...
Creating jupyterhub-db
Creating jupyterhub
Starting up log tracking (Press ctrl-C to stop tracking, JupyterHub will continue running.)
...
Attaching to jupyterhub, jupyterhub-db
jupyterhub-db | 2019-06-24T16:19:06.803982876Z LOG:  database system was shut down at 2019-06-24 16:09:32 UTC
jupyterhub-db | 2019-06-24T16:19:06.806134717Z LOG:  MultiXact member wraparound protections are now enabled
jupyterhub-db | 2019-06-24T16:19:06.807719800Z LOG:  database system is ready to accept connections
jupyterhub-db | 2019-06-24T16:19:06.807731237Z LOG:  autovacuum launcher started
jupyterhub | 2019-06-24T16:19:08.150462878Z [I 2019-06-24 16:19:08.150 JupyterHub app:2120] Using Authenticator: tmpauthenticator.TmpAuthenticator
jupyterhub | 2019-06-24T16:19:08.150513556Z [I 2019-06-24 16:19:08.150 JupyterHub app:2120] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.9.1
jupyterhub | 2019-06-24T16:19:08.152858499Z [I 2019-06-24 16:19:08.152 JupyterHub app:1257] Loading cookie_secret from /data/jupyterhub_cookie_secret
jupyterhub | 2019-06-24T16:19:08.170979610Z Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
jupyterhub | 2019-06-24T16:19:08.187603213Z ERROR:asyncio:Task exception was never retrieved
jupyterhub | 2019-06-24T16:19:08.187622153Z future: <Task finished coro=<launch_instance_async() done, defined at /opt/conda/lib/python3.5/site-packages/jupyterhub/app.py:2477> exception=SystemExit(DatabaseSchemaMismatch('Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.',),)>
jupyterhub | 2019-06-24T16:19:08.187626810Z Traceback (most recent call last):
jupyterhub | 2019-06-24T16:19:08.187628733Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 2492, in launch_instance
jupyterhub | 2019-06-24T16:19:08.187630659Z     loop.start()
jupyterhub | 2019-06-24T16:19:08.187632434Z   File "/opt/conda/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 148, in start
jupyterhub | 2019-06-24T16:19:08.187634329Z     self.asyncio_loop.run_forever()
jupyterhub | 2019-06-24T16:19:08.187636049Z   File "/opt/conda/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
jupyterhub | 2019-06-24T16:19:08.187637812Z     self._run_once()
jupyterhub | 2019-06-24T16:19:08.187639499Z   File "/opt/conda/lib/python3.5/asyncio/base_events.py", line 1425, in _run_once
jupyterhub | 2019-06-24T16:19:08.187641352Z     handle._run()
jupyterhub | 2019-06-24T16:19:08.187643039Z   File "/opt/conda/lib/python3.5/asyncio/events.py", line 127, in _run
jupyterhub | 2019-06-24T16:19:08.187644775Z     self._callback(*self._args)
jupyterhub | 2019-06-24T16:19:08.187646460Z   File "/opt/conda/lib/python3.5/asyncio/tasks.py", line 240, in _step
jupyterhub | 2019-06-24T16:19:08.187648219Z     result = coro.send(None)
jupyterhub | 2019-06-24T16:19:08.187649902Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
jupyterhub | 2019-06-24T16:19:08.187651739Z     await self.initialize(argv)
jupyterhub | 2019-06-24T16:19:08.187653431Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 2129, in initialize
jupyterhub | 2019-06-24T16:19:08.187655310Z     self.init_db()
jupyterhub | 2019-06-24T16:19:08.187657342Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1449, in init_db
jupyterhub | 2019-06-24T16:19:08.187659212Z     self.exit(e)
jupyterhub | 2019-06-24T16:19:08.187660914Z   File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 648, in exit
jupyterhub | 2019-06-24T16:19:08.187662777Z     sys.exit(exit_status)
jupyterhub | 2019-06-24T16:19:08.187664428Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/app.py", line 1430, in init_db
jupyterhub | 2019-06-24T16:19:08.187674459Z     self.db_url, reset=self.reset_db, echo=self.debug_db, **self.db_kwargs
jupyterhub | 2019-06-24T16:19:08.187676507Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 814, in new_session_factory
jupyterhub | 2019-06-24T16:19:08.187678385Z     check_db_revision(engine)
jupyterhub | 2019-06-24T16:19:08.187680198Z   File "/opt/conda/lib/python3.5/site-packages/jupyterhub/orm.py", line 756, in check_db_revision
jupyterhub | 2019-06-24T16:19:08.187682221Z     found=alembic_revision, head=head
jupyterhub | 2019-06-24T16:19:08.187684471Z SystemExit: Found database schema version 896818069c98 != 4dc2d5a8c53c. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
jupyterhub exited with code 1
````

This error persists even if I go back to a single user image which is the jupyter/minimal-notebook without any additions, and do 
````
$ docker system prune -a
````

I have not changed any settings in the postgresql or jupyterhub Dockerfiles or settings, so I am quite baffled and can't find a way to proceed.
I've seen that there was a previous similar issue #43, but no solution is given there.
Any pointer or help would be appreciated.

**Comment by dalg24** [comment]
The log is telling you what to do
```
Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
jupyterhub exited with code 1
```

Try something like `docker-compose run --rm hub jupyterhub upgrade-db`

**Comment by Heerpa** [comment]
Great thanks - I was not aware where to execute this. I ended up putting
````
CMD ["jupyterhub" "update-db"]
````

at the end of the Dockerfile for my jupyterhub. Now everything is back to working nicely.
